# Splunk SIEM Configuration
splunk:
  host: "REPLACE_WITH_YOUR_SPLUNK_HOST"
  port: 8089
  username: "REPLACE_WITH_YOUR_USERNAME"
  password: "REPLACE_WITH_YOUR_PASSWORD"
  # OR use token-based auth
  token: "REPLACE_WITH_YOUR_API_TOKEN"
  verify_ssl: true
  default_index: "security"

# Search Configuration
search:
  max_results: 10000
  timeout: 300
  earliest_time: "-24h"
  latest_time: "now"

# Alert Configuration
alerts:
  email_notifications: true
  webhook_url: "https://your-webhook-endpoint.com"
  severity_levels:
    - critical
    - high
    - medium
    - low